/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CompoundPriceOracleMockInterface extends ethers.utils.Interface {
  functions: {
    "MANTISSA()": FunctionFragment;
    "cTokenPrices(address)": FunctionFragment;
    "getPriceUpdate(address)": FunctionFragment;
    "getUnderlyingPrice(address)": FunctionFragment;
    "isPriceOracle()": FunctionFragment;
    "originalOracle()": FunctionFragment;
    "setOriginalOracle(address)": FunctionFragment;
    "setPriceUpdate(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "MANTISSA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cTokenPrices",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceUpdate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnderlyingPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "originalOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOriginalOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceUpdate",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MANTISSA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cTokenPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnderlyingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "originalOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOriginalOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceUpdate",
    data: BytesLike
  ): Result;

  events: {};
}

export class CompoundPriceOracleMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CompoundPriceOracleMockInterface;

  functions: {
    MANTISSA(overrides?: CallOverrides): Promise<[BigNumber]>;

    cTokenPrices(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getPriceUpdate(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUnderlyingPrice(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isPriceOracle(overrides?: CallOverrides): Promise<[boolean]>;

    originalOracle(overrides?: CallOverrides): Promise<[string]>;

    setOriginalOracle(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPriceUpdate(
      cToken: string,
      priceUpdate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  MANTISSA(overrides?: CallOverrides): Promise<BigNumber>;

  cTokenPrices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getPriceUpdate(cToken: string, overrides?: CallOverrides): Promise<BigNumber>;

  getUnderlyingPrice(
    cToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isPriceOracle(overrides?: CallOverrides): Promise<boolean>;

  originalOracle(overrides?: CallOverrides): Promise<string>;

  setOriginalOracle(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPriceUpdate(
    cToken: string,
    priceUpdate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MANTISSA(overrides?: CallOverrides): Promise<BigNumber>;

    cTokenPrices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPriceUpdate(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnderlyingPrice(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPriceOracle(overrides?: CallOverrides): Promise<boolean>;

    originalOracle(overrides?: CallOverrides): Promise<string>;

    setOriginalOracle(addr: string, overrides?: CallOverrides): Promise<void>;

    setPriceUpdate(
      cToken: string,
      priceUpdate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    MANTISSA(overrides?: CallOverrides): Promise<BigNumber>;

    cTokenPrices(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPriceUpdate(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnderlyingPrice(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPriceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    originalOracle(overrides?: CallOverrides): Promise<BigNumber>;

    setOriginalOracle(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPriceUpdate(
      cToken: string,
      priceUpdate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MANTISSA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cTokenPrices(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceUpdate(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnderlyingPrice(
      cToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPriceOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    originalOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setOriginalOracle(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPriceUpdate(
      cToken: string,
      priceUpdate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
