/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface FundsManagerInterface extends ethers.utils.Interface {
  functions: {
    "holder()": FunctionFragment;
    "principal()": FunctionFragment;
    "profit()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "holder", values?: undefined): string;
  encodeFunctionData(functionFragment: "principal", values?: undefined): string;
  encodeFunctionData(functionFragment: "profit", values?: undefined): string;

  decodeFunctionResult(functionFragment: "holder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "principal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profit", data: BytesLike): Result;

  events: {
    "FundsWithdrawal(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FundsWithdrawal"): EventFragment;
}

export type FundsWithdrawalEvent = TypedEvent<
  [BigNumber, BigNumber] & {
    withdrawAmount: BigNumber;
    principalFactor: BigNumber;
  }
>;

export class FundsManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FundsManagerInterface;

  functions: {
    holder(overrides?: CallOverrides): Promise<[string]>;

    principal(overrides?: CallOverrides): Promise<[BigNumber]>;

    profit(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  holder(overrides?: CallOverrides): Promise<string>;

  principal(overrides?: CallOverrides): Promise<BigNumber>;

  profit(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    holder(overrides?: CallOverrides): Promise<string>;

    principal(overrides?: CallOverrides): Promise<BigNumber>;

    profit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "FundsWithdrawal(uint256,uint256)"(
      withdrawAmount?: null,
      principalFactor?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { withdrawAmount: BigNumber; principalFactor: BigNumber }
    >;

    FundsWithdrawal(
      withdrawAmount?: null,
      principalFactor?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { withdrawAmount: BigNumber; principalFactor: BigNumber }
    >;
  };

  estimateGas: {
    holder(overrides?: CallOverrides): Promise<BigNumber>;

    principal(overrides?: CallOverrides): Promise<BigNumber>;

    profit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    holder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    principal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    profit(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
