/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ISimplePositionStopLossConnectorInterface
  extends ethers.utils.Interface {
  functions: {
    "configureStopLoss(uint256,uint256,uint256)": FunctionFragment;
    "executeStopLoss()": FunctionFragment;
    "getStopLossConfiguration()": FunctionFragment;
    "getStopLossState()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "configureStopLoss",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeStopLoss",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStopLossConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStopLossState",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "configureStopLoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeStopLoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStopLossConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStopLossState",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISimplePositionStopLossConnector extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISimplePositionStopLossConnectorInterface;

  functions: {
    configureStopLoss(
      unwindFactor: BigNumberish,
      slippageIncentive: BigNumberish,
      collateralUsageLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeStopLoss(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getStopLossConfiguration(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        slippageIncentive: BigNumber;
        collateralUsageLimit: BigNumber;
        unwindFactor: BigNumber;
      }
    >;

    getStopLossState(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  configureStopLoss(
    unwindFactor: BigNumberish,
    slippageIncentive: BigNumberish,
    collateralUsageLimit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeStopLoss(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getStopLossConfiguration(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      slippageIncentive: BigNumber;
      collateralUsageLimit: BigNumber;
      unwindFactor: BigNumber;
    }
  >;

  getStopLossState(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    configureStopLoss(
      unwindFactor: BigNumberish,
      slippageIncentive: BigNumberish,
      collateralUsageLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    executeStopLoss(overrides?: CallOverrides): Promise<BigNumber>;

    getStopLossConfiguration(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        slippageIncentive: BigNumber;
        collateralUsageLimit: BigNumber;
        unwindFactor: BigNumber;
      }
    >;

    getStopLossState(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        canTriggerStopLoss: boolean;
        supplyBalance: BigNumber;
        borrowBalance: BigNumber;
        slippageIncentive: BigNumber;
        collateralUsageLimit: BigNumber;
        unwindFactor: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    configureStopLoss(
      unwindFactor: BigNumberish,
      slippageIncentive: BigNumberish,
      collateralUsageLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeStopLoss(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getStopLossConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getStopLossState(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    configureStopLoss(
      unwindFactor: BigNumberish,
      slippageIncentive: BigNumberish,
      collateralUsageLimit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeStopLoss(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getStopLossConfiguration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStopLossState(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
