/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDecreaseWithV3FlashswapMultihopConnector,
  IDecreaseWithV3FlashswapMultihopConnectorInterface,
} from "../IDecreaseWithV3FlashswapMultihopConnector";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "withdrawAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxSupplyTokenRepayAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowTokenRepayAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "platform",
            type: "address",
          },
          {
            internalType: "address",
            name: "supplyToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "borrowToken",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "path",
            type: "bytes",
          },
        ],
        internalType: "struct DecreaseWithV3FlashswapMultihopConnectorParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "decreasePositionWithV3FlashswapMultihop",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDecreaseWithV3FlashswapMultihopConnector__factory {
  static readonly abi = _abi;
  static createInterface(): IDecreaseWithV3FlashswapMultihopConnectorInterface {
    return new utils.Interface(
      _abi
    ) as IDecreaseWithV3FlashswapMultihopConnectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDecreaseWithV3FlashswapMultihopConnector {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDecreaseWithV3FlashswapMultihopConnector;
  }
}
