/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IFodlNFTProvider,
  IFodlNFTProviderInterface,
} from "../IFodlNFTProvider";

const _abi = [
  {
    inputs: [],
    name: "fodlNFT",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFodlNFTProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IFodlNFTProviderInterface {
    return new utils.Interface(_abi) as IFodlNFTProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFodlNFTProvider {
    return new Contract(address, _abi, signerOrProvider) as IFodlNFTProvider;
  }
}
