/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IIncreaseWithV3FlashswapMultihopConnector,
  IIncreaseWithV3FlashswapMultihopConnectorInterface,
} from "../IIncreaseWithV3FlashswapMultihopConnector";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "principalAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "supplyAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxBorrowAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "platform",
            type: "address",
          },
          {
            internalType: "address",
            name: "supplyToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "borrowToken",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "path",
            type: "bytes",
          },
        ],
        internalType: "struct IncreaseWithV3FlashswapMultihopParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "increasePositionWithV3FlashswapMultihop",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IIncreaseWithV3FlashswapMultihopConnector__factory {
  static readonly abi = _abi;
  static createInterface(): IIncreaseWithV3FlashswapMultihopConnectorInterface {
    return new utils.Interface(
      _abi
    ) as IIncreaseWithV3FlashswapMultihopConnectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIncreaseWithV3FlashswapMultihopConnector {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IIncreaseWithV3FlashswapMultihopConnector;
  }
}
