/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILendingPlatformBSC,
  ILendingPlatformBSCInterface,
} from "../ILendingPlatformBSC";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "platform",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "platform",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "redeemAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILendingPlatformBSC__factory {
  static readonly abi = _abi;
  static createInterface(): ILendingPlatformBSCInterface {
    return new utils.Interface(_abi) as ILendingPlatformBSCInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILendingPlatformBSC {
    return new Contract(address, _abi, signerOrProvider) as ILendingPlatformBSC;
  }
}
