/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISimplePositionFoldingConnector,
  ISimplePositionFoldingConnectorInterface,
} from "../ISimplePositionFoldingConnector";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "platform",
        type: "address",
      },
      {
        internalType: "address",
        name: "supplyToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "withdrawAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxRedeemAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "borrowToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "minRepayAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "exchangeData",
        type: "bytes",
      },
    ],
    name: "decreaseSimplePositionWithLoop",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "platform",
        type: "address",
      },
      {
        internalType: "address",
        name: "supplyToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "principalAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minSupplyAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "borrowToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalBorrowAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "exchangeData",
        type: "bytes",
      },
    ],
    name: "increaseSimplePositionWithLoop",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISimplePositionFoldingConnector__factory {
  static readonly abi = _abi;
  static createInterface(): ISimplePositionFoldingConnectorInterface {
    return new utils.Interface(
      _abi
    ) as ISimplePositionFoldingConnectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISimplePositionFoldingConnector {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISimplePositionFoldingConnector;
  }
}
