/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISimplePositionStopLossConnector,
  ISimplePositionStopLossConnectorInterface,
} from "../ISimplePositionStopLossConnector";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "unwindFactor",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "slippageIncentive",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "collateralUsageLimit",
        type: "uint256",
      },
    ],
    name: "configureStopLoss",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "executeStopLoss",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getStopLossConfiguration",
    outputs: [
      {
        internalType: "uint256",
        name: "slippageIncentive",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "collateralUsageLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "unwindFactor",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStopLossState",
    outputs: [
      {
        internalType: "bool",
        name: "canTriggerStopLoss",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "supplyBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "borrowBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "slippageIncentive",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "collateralUsageLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "unwindFactor",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISimplePositionStopLossConnector__factory {
  static readonly abi = _abi;
  static createInterface(): ISimplePositionStopLossConnectorInterface {
    return new utils.Interface(
      _abi
    ) as ISimplePositionStopLossConnectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISimplePositionStopLossConnector {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISimplePositionStopLossConnector;
  }
}
