/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISimplePositionBaseConnector,
  ISimplePositionBaseConnectorInterface,
} from "../ISimplePositionBaseConnector";

const _abi = [
  {
    inputs: [],
    name: "getBorrowBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCollateralUsageFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getPositionMetadata",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "supplyAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "collateralUsageFactor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "principalValue",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "positionValue",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "positionAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "platformAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "supplyTokenAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "borrowTokenAddress",
            type: "address",
          },
        ],
        internalType: "struct SimplePositionMetadata",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getPositionValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getPrincipalValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getSimplePositionDetails",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSupplyBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISimplePositionBaseConnector__factory {
  static readonly abi = _abi;
  static createInterface(): ISimplePositionBaseConnectorInterface {
    return new utils.Interface(_abi) as ISimplePositionBaseConnectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISimplePositionBaseConnector {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISimplePositionBaseConnector;
  }
}
